# Task:
**Create arrays with all the data types Available in numpy**
- Numpy has 11 Datatypes and the characters used to represent them are:

- integer - i
- boolean - ?
- unsigned integer - u
- float - f
- complex float - c
- timedelta - m
- datetime - M
- object - O
- string - S
- unicode string - U
- fixed chunk of memory for other type (void) - V** 

### Int Datatype

In [4]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
a.dtype

[1 2 3 4]


dtype('int32')

In [5]:
a=np.array([-1,0,1,2,3,4],dtype='intc')
print(a)
a.dtype

[-1  0  1  2  3  4]


dtype('int32')

In [6]:
a=np.array([-1,0,1,2,3,4],dtype='int_')
print(a)
a.dtype

[-1  0  1  2  3  4]


dtype('int32')

In [11]:
a=np.array([-1,0,1,2,3,4],dtype='longlong')
print(a)
a.dtype

[-1  0  1  2  3  4]


dtype('int64')

### Boolean Datatype

In [9]:
a=np.array([-1,0,1,2,3,4],dtype='?')
print(a)
a.dtype

[ True False  True  True  True  True]


dtype('bool')

In [12]:
a=np.array([-1,0,1,2,3,4],dtype='bool')
print(a)
a.dtype

[ True False  True  True  True  True]


dtype('bool')

### Unsigned int Datatype

In [13]:
a=np.array([-1,0,1,2,3,4],dtype='uint')
print(a)
a.dtype

[4294967295          0          1          2          3          4]


dtype('uint32')

In [14]:
a=np.array([-1,0,1,2,3,4],dtype='uintc')
print(a)
a.dtype

[4294967295          0          1          2          3          4]


dtype('uint32')

In [15]:
a=np.array([-1,0,1,2,3,4],dtype='uint8')
print(a)
a.dtype

[255   0   1   2   3   4]


dtype('uint8')

In [16]:
a=np.array([-1,0,1,2,3,4],dtype='uint16')
print(a)
a.dtype

[65535     0     1     2     3     4]


dtype('uint16')

In [17]:
a=np.array([-1,0,1,2,3,4],dtype='uint32')
print(a)
a.dtype

[4294967295          0          1          2          3          4]


dtype('uint32')

In [18]:
a=np.array([-1,0,1,2,3,4],dtype='uint64')
print(a)
a.dtype

[18446744073709551615                    0                    1
                    2                    3                    4]


dtype('uint64')

In [19]:
a=np.array([-1,0,1,2,3,4],dtype='ulonglong')
print(a)
a.dtype

[18446744073709551615                    0                    1
                    2                    3                    4]


dtype('uint64')

### Float Datatype

In [21]:
a=np.array([1.32 , 2 , 6.46 , 2])
print(a)
a.dtype

[1.32 2.   6.46 2.  ]


dtype('float64')

In [22]:
a=np.array([-1,0,1,2,3,4],dtype='f')
print(a)
a.dtype

[-1.  0.  1.  2.  3.  4.]


dtype('float32')

In [23]:
a=np.array([-1,0,1,2,3,4],dtype='half')
print(a)
a.dtype

[-1.  0.  1.  2.  3.  4.]


dtype('float16')

In [24]:
a=np.array([-1,0,1,2,3,4],dtype='single')
print(a)
a.dtype

[-1.  0.  1.  2.  3.  4.]


dtype('float32')

In [25]:
a=np.array([-1,0,1,2,3,4],dtype='double')
print(a)
a.dtype

[-1.  0.  1.  2.  3.  4.]


dtype('float64')

In [26]:
a=np.array([-1,0,1,2,3,4],dtype='longdouble')
print(a)
a.dtype

[-1.  0.  1.  2.  3.  4.]


dtype('float64')

### Complex float Datatype

In [30]:
a=np.array([-1-2j,1.32+6j,4+6j,2.64+6j])
print(a)
a.dtype

[-1.  -2.j  1.32+6.j  4.  +6.j  2.64+6.j]


dtype('complex128')

In [32]:
a=np.array([-1,0,1,2,3,4],dtype='csingle')
print(a)
a.dtype

[-1.+0.j  0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j]


dtype('complex64')

In [33]:
a=np.array([-1,0,1,2,3,4],dtype='cdouble')
print(a)
a.dtype

[-1.+0.j  0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j]


dtype('complex128')

In [34]:
a=np.array([-1,0,1,2,3,4],dtype='clongdouble')
print(a)
a.dtype

[-1.+0.j  0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j]


dtype('complex128')

### Timedelta Datatype

In [35]:
a=np.timedelta64(11,'M')
print(a)
a.dtype

11 months


dtype('<m8[M]')

In [43]:
a=np.timedelta64(11,'D')
print(a)
print(a.dtype)

11 days
timedelta64[D]


In [44]:
a=np.timedelta64(11,'W')
print(a)
print(a.dtype)

11 weeks
timedelta64[W]


In [45]:
a=np.timedelta64(11,'m')
print(a)
print(a.dtype)

11 minutes
timedelta64[m]


In [46]:
a=np.timedelta64(11,'s')
print(a)
print(a.dtype)

11 seconds
timedelta64[s]


In [47]:
a=np.timedelta64(11,'h')
print(a)
print(a.dtype)

11 hours
timedelta64[h]


In [50]:
a = np.array([2001-12-23,2001-2-3], dtype='m')
print(a)
print(a.dtype)

[1966 1996]
timedelta64


### Datetime DataType

In [51]:
a = np.array(['2010-07-11', '2006-01-13'])
print(a)
print(a.dtype)

['2010-07-11' '2006-01-13']
<U10


In [52]:
a = np.array(['2010-07-11', '2006-01-13','2001-12-23'],dtype='datetime64')
print(a)
print(a.dtype)

['2010-07-11' '2006-01-13' '2001-12-23']
datetime64[D]


In [53]:
a = np.array(['2010-07-11', '2006-01-13', '2010-08-13'], dtype='M')
print(a)
print(a.dtype)

['2010-07-11' '2006-01-13' '2010-08-13']
datetime64[D]


### Object Datatype

In [56]:
a = np.array(['Manish',2,3,4], dtype='O')
print(a)
print(a.dtype)

['Manish' 2 3 4]
object


In [57]:
a = np.array([1,2,3,4], dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [58]:
a = np.array(['Sundar', 'Shyam', 'Manish', 'Tarun'])
print(a)
print(a.dtype)

['Sundar' 'Shyam' 'Manish' 'Tarun']
<U6


### Unicode string DataType

In [59]:
a = np.array([u'\u0065', u'\u0123', u'\265F', u'\u2202r'])
print(a)
print(a.dtype)

['e' 'ģ' 'µF' '∂r']
<U2


In [60]:
a = np.array([u'\u0394', u'\265E', u'\265F', u'\u2202r'], dtype='U')
print(a)
print(a.dtype)

['Δ' 'µE' 'µF' '∂r']
<U2


### Void DataType

In [ ]:
a = np.array([], dtype='V')
print(a)
print(a.dtype)